version: '3.1'
services:
  stats-server:
    build: stats
    image: stats
    #container_name: stats_cont
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/stats
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SERVER_PORT=9090

  stats-db:
    image: postgres:14-alpine
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  ewm-service:
    build: ewm
    image: ewm
    #container_name: ewm_cont
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/ewm
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - STATS_SERVER_URL=http://stats-server:9090

  ewm-db:
    image: postgres:14-alpine
    ports:
      - "6542:5433"
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres