CREATE TABLE IF NOT EXISTS "users" (
                                       "id" SERIAL PRIMARY KEY,
                                       "email" varchar(50) NOT NULL,
    "name" varchar(100) NOT NULL
    );

CREATE TABLE IF NOT EXISTS "categories" (
                                            "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                            "name" varchar(50) NOT NULL
    );

CREATE TABLE IF NOT EXISTS "events" (
    "id" SERIAL PRIMARY KEY,
    "title" varchar(120) NOT NULL,
    "annotation" varchar(2000),
    "description" varchar(7000),
    "category_id" int NOT NULL,
    "event_date" timestamp NOT NULL,
    "paid" boolean DEFAULT false,
    "request_moderation" boolean DEFAULT true,
    "confirmed_requests" int,
    "participant_limit" int,
    "initiator_id" BIGINT NOT NULL,
    "created_on" timestamp NOT NULL,
    "published_on" timestamp,
    "event_state" varchar,
    "lon" float,
    "lat" float
    );

CREATE TABLE IF NOT EXISTS "event_requests" (
                                                "id" SERIAL PRIMARY KEY,
                                                "user_id" BIGINT NOT NULL,
                                                "event_id" BIGINT NOT NULL,
                                                "status" varchar,
                                                "created" timestamp NOT NULL
);

CREATE TABLE IF NOT EXISTS "compilations" (
                                              "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                              "pinned" boolean DEFAULT false,
                                              "title" varchar(200) NOT NULL
    );

CREATE TABLE IF NOT EXISTS "compilation_event_link" (
                                                        "compilation_id" int NOT NULL,
                                                        "event_id" BIGINT NOT NULL
);

ALTER TABLE "events" ADD FOREIGN KEY ("category_id") REFERENCES "categories" ("id");

ALTER TABLE "events" ADD FOREIGN KEY ("initiator_id") REFERENCES "users" ("id");

ALTER TABLE "event_requests" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "event_requests" ADD FOREIGN KEY ("event_id") REFERENCES "events" ("id");

ALTER TABLE "compilation_event_link" ADD FOREIGN KEY ("event_id") REFERENCES "events" ("id");

ALTER TABLE "compilation_event_link" ADD FOREIGN KEY ("compilation_id") REFERENCES "compilations" ("id");


